services:
  app:
    build:
      context: .
      args:
        GIT_HASH: ${GIT_HASH:-unknown}
    restart: always
    environment:
      CLICOLOR_FORCE: ${CLICOLOR_FORCE:-0}
      POSTGRES_HOST: ${POSTGRES_HOST:-postgres}
      POSTGRES_DB: ${POSTGRES_DB:?}
      POSTGRES_USER: ${POSTGRES_USER:?}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:?}
      REDIS_HOST: ${REDIS_HOST:-redis}
      REDIS_PASSWORD: ${REDIS_PASSWORD:?}
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./.data/attachments:/app/attachments
    networks:
      - default
      - internal

  postgres:
    image: postgres:18-alpine
    restart: always
    ports:
      - "${POSTGRES_PORT:-5432}:5432"
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      PGDATA: /var/lib/postgresql/18/data/pgdata
    volumes:
      - ./.data/pg_data:/var/lib/postgresql/18/data
    networks:
      - internal
      - default #! Debugging

  adminer:
    image: adminer:5
    restart: always
    ports:
      - "${ADMINER_PORT:-8000}:8080"
    networks:
      - internal
      - default

  redis:
    image: redis:8-alpine
    restart: always
    command: ["redis-server", "--requirepass", "${REDIS_PASSWORD}"]
    ports:
      - "${REDIS_PORT:-6379}:6379"
    volumes:
      - ./.data/redis_data:/data
    networks:
      - internal
      - default #! Debugging

  registry:
    image: registry:3
    restart: always
    ports:
      - "127.0.0.1:${REGISTRY_PORT:-5000}:5000"
    volumes:
      - ./registry/config.yml:/etc/distribution/config.yml:ro
      - ./registry/gc.sh:/gc.sh:ro
      - ./.data/registry_data:/var/lib/registry
    networks:
      - default

  registry-ui:
    image: joxit/docker-registry-ui:2.6
    restart: always
    environment:
      SINGLE_REGISTRY: "true"
      REGISTRY_TITLE: "Docker Registry"
      DELETE_IMAGES: "true"
      NGINX_PROXY_PASS_URL: "http://registry:5000"
      SHOW_CONTENT_DIGEST: "true"
      SHOW_CATALOG_NB_TAGS: "true"
    networks:
      - default

  traefik:
    image: traefik:v3.6
    restart: always
    environment:
      - BASIC_AUTH_USERNAME=${BASIC_AUTH_USERNAME:?}
      - BASIC_AUTH_HTPASSWORD=${BASIC_AUTH_HTPASSWORD:?}
    ports:
      - "80:80"
      - "443:443"
      - "5443:5443"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./traefik/traefik.yml:/etc/traefik/traefik.yml:ro
      - ./traefik/dynamic.yml:/etc/traefik/dynamic.yml:ro
    networks:
      default:
      trxd-shared-internal:
        ipv4_address: 172.137.0.2


networks:
  default:
  internal:
    internal: true
  trxd-shared-internal:
    external: true
