http:
  services:
    app:
      loadBalancer:
        servers:
          - url: "http://app:1337"

    adminer:
      loadBalancer:
        servers:
          - url: "http://adminer:8080"
    
    registry:
      loadBalancer:
        servers:
          - url: "http://registry:5000"
    
    registry-ui:
      loadBalancer:
        servers:
          - url: "http://registry-ui:80"


  routers:
    #! #################### App #################### !#
    app:
      service: app
      rule: "PathPrefix(`/`)"
      entryPoints:
        - web
      priority: 1

    app-instances:
      service: app
      rule: "Path(`/api/instances`)"
      entryPoints:
        - web
      priority: 10
      middlewares:
        - app-instances-ratelimit

    app-submissions:
      service: app
      rule: "Path(`/api/submissions`) && Method(`POST`)"
      entryPoints:
        - web
      priority: 10
      middlewares:
        - app-submissions-ratelimit

    #! #################### Traefik API #################### !#
    traefik-api-http:
      service: api@internal
      rule: "HostRegexp(`^traefik\\..+$`)"
      entryPoints:
        - web
      priority: 10
      middlewares:
        - https-redirect

    traefik-api:
      service: api@internal
      rule: "HostRegexp(`^traefik\\..+$`)"
      tls: {}
      entryPoints:
        - websecure
      priority: 10
      middlewares:
        - basic-auth

    #! #################### Adminer #################### !#
    adminer-http:
      service: adminer
      rule: "HostRegexp(`^adminer\\..+$`)"
      entryPoints:
        - web
      priority: 10
      middlewares:
        - https-redirect

    adminer:
      service: adminer
      rule: "HostRegexp(`^adminer\\..+$`)"
      tls: {}
      entryPoints:
        - websecure
      priority: 10
      middlewares:
        - basic-auth
    
    #! #################### Registry #################### !#
    registry-http:
      service: registry
      rule: "HostRegexp(`^registry\\..+$`)"
      entryPoints:
        - web
      priority: 10
      middlewares:
        - https-redirect

    registry:
      service: registry
      rule: "HostRegexp(`^registry\\..+$`)"
      tls: {}
      entryPoints:
        - websecure
      priority: 10
      middlewares:
        - basic-auth
    
    #! #################### Registry UI #################### !#
    registry-ui-http:
      service: registry-ui
      rule: "HostRegexp(`^registry-ui\\..+$`)"
      entryPoints:
        - web
      priority: 10
      middlewares:
        - https-redirect

    registry-ui:
      service: registry-ui
      rule: "HostRegexp(`^registry-ui\\..+$`)"
      tls: {}
      entryPoints:
        - websecure
      priority: 10
      middlewares:
        - basic-auth


  middlewares:
    #! #################### Common Middlewares #################### !#
    https-redirect:
      redirectScheme:
        scheme: https
        permanent: true

    basic-auth:
      basicAuth:
        users:
          - '{{ env "BASIC_AUTH_USERNAME" }}:{{ env "BASIC_AUTH_HTPASSWD" }}'

    #! #################### App Rate limits #################### !#
    app-instances-ratelimit:
      rateLimit:
        average: 1
        burst: 10
        period: 60s
        sourceCriterion:
          requestHeaderName: "CF-Connecting-IP"

    app-submissions-ratelimit:
      rateLimit:
        average: 2
        burst: 10
        period: 10s
        sourceCriterion:
          requestHeaderName: "CF-Connecting-IP"

