package consts

import "regexp"

const (
	MinPasswordLength        = 8
	MaxPasswordLength        = 64
	MaxNameLength            = 64
	MaxEmailLength           = 256
	MaxFlagLength            = 128
	MaxCategoryLength        = 32
	MaxIconLength            = 32
	MaxChallNameLength       = 128
	MaxChallDescLength       = 1024
	MaxChallDifficultyLength = 16
	MaxCountryLength         = 3
	MinPort                  = 1
	MaxPort                  = 65535
	MaxTagNameLength         = 32
)

const (
	EndpointNotFound            = "Endpoint not found"
	InvalidJSON                 = "Invalid JSON format"
	MissingRequiredFields       = "Missing required fields"
	ShortPassword               = "Password must be at least 8 characters long"
	LongPassword                = "Password must not exceed 64 characters"
	LongName                    = "Name must not exceed 64 characters"
	LongEmail                   = "Email must not exceed 256 characters"
	InvalidEmail                = "Invalid email format"
	UserAlreadyExists           = "User already exists"
	ErrorRegisteringUser        = "Error registering user"
	ErrorFetchingSession        = "Error fetching session"
	ErrorSavingSession          = "Error saving session"
	ErrorDestroyingSession      = "Error destroying session"
	ErrorLoggingIn              = "Error logging in"
	InvalidCredentials          = "Invalid email or password"
	Unauthorized                = "Unauthorized"
	AlreadyInTeam               = "Already in a team"
	ErrorRegisteringTeam        = "Error registering team"
	TeamAlreadyExists           = "Team already exists"
	ErrorFetchingTeam           = "Error fetching team"
	InvalidTeamCredentials      = "Invalid name or password"
	LongFlag                    = "Flag must not exceed 128 characters"
	ErrorFetchingChallenge      = "Error fetching challenge"
	ChallengeNotFound           = "Challenge not found"
	ErrorSubmittingFlag         = "Error submitting flag"
	LongCategory                = "Category must not exceed 32 characters"
	LongIcon                    = "Icon must not exceed 32 characters"
	ErrorCreatingCategory       = "Error creating category"
	CategoryAlreadyExists       = "Category already exists"
	ErrorFetchingUser           = "Error fetching user"
	ErrorCreatingChallenge      = "Error creating challenge"
	ChallengeAlreadyExists      = "Challenge already exists"
	LongChallName               = "Challenge name must not exceed 128 characters"
	LongChallDesc               = "Challenge description must not exceed 1024 characters"
	InvalidChallType            = "Invalid challenge type, must be one of: Normal, Container, Compose"
	InvalidChallMaxPoints       = "Max points must be non negative"
	InvalidChallScoreType       = "Invalid challenge score type, must be one of: Static, Dynamic"
	CategoryNotFound            = "Category not found"
	ErrorCreatingFlag           = "Error creating flag"
	FlagAlreadyExists           = "Flag already exists"
	ErrorUpdatingConfig         = "Error updating configuration"
	ConfigNotFound              = "Configuration not found"
	ErrorUpdatingUser           = "Error updating user"
	LongCountry                 = "Country must not exceed 3 characters"
	ErrorDeletingCategory       = "Error deleting category"
	ErrorDeletingChallenge      = "Error deleting challenge"
	InvalidChallengeID          = "Invalid challenge ID, must be non negative"
	ErrorGeneratingPassword     = "Error generating random password"
	InvalidTeamID               = "Invalid team ID, must be non negative"
	ErrorResettingTeamPassword  = "Error resetting team password"
	InvalidUserID               = "Invalid user ID, must be non negative"
	ErrorResettingUserPassword  = "Error resetting user password"
	ErrorDeletingFlag           = "Error deleting flag"
	ErrorFetchingConfig         = "Error fetching configuration"
	DisabledRegistration        = "Registration is disabled"
	ErrorFetchingChallenges     = "Error fetching challenges"
	UserNotFound                = "User not found"
	TeamNotFound                = "Team not found"
	AlreadyRegistered           = "Already registered"
	AlreadyLoggedIn             = "Already logged in"
	NotLoggedIn                 = "Not logged in"
	Forbidden                   = "Forbidden"
	ErrorFetchingCategory       = "Error fetching category"
	ErrorUpdatingCategory       = "Error updating category"
	InvalidMultipartForm        = "Invalid multipart form"
	InvalidFormData             = "Invalid form data"
	ErrorUpdatingChallenge      = "Error updating challenge"
	InvalidFilePath             = "Invalid file path"
	LongChallDifficulty         = "Challenge difficulty must not exceed 16 characters"
	InvalidPort                 = "Port must be between 1 and 65535"
	InvalidLifetime             = "Lifetime must be greater than 0"
	InvalidEnvs                 = "Invalid environment variables"
	InvalidMaxMemory            = "Max memory must be greater than 0"
	InvalidMaxCpu               = "Max CPU must be a positive number"
	ChallIDRequired             = "Challenge ID is required"
	NoDataToUpdate              = "No data provided to update"
	ErrorCreatingAttachmentsDir = "Error creating attachments directory"
	ErrorSavingFile             = "Error saving file"
	ChallNameExists             = "Challenge name already exists"
	LongTagName                 = "Tag name must not exceed 32 characters"
	TagAlreadyExists            = "Tag already exists"
	ErrorCreatingTag            = "Error creating tag"
	ErrorDeletingTag            = "Error deleting tag"
	ErrorUpdatingTag            = "Error updating tag"
	ErrorFetchingConfigs        = "Error fetching configurations"
	ChallengeNotInstanciable    = "Challenge is not instanciable"
	ErrorFetchingInstance       = "Error fetching instance"
	AlreadyAnActiveInstance     = "Already an active instance"
	ErrorCreatingInstance       = "Error creating instance"
	MissingLifetime             = "global lifetime is missing"
	DisabledInstances           = "instances are disabled"
	ErrorDeletingInstance       = "Error deleting instance"
	InstanceNotFound            = "Instance not found"
	InvalidImage                = "Invalid image"
)

var UserRegex = regexp.MustCompile(`(^[^@\s]+@[^@\s]+\.[^@\s]+$)`)

const Separator = "," // TODO: change separator
