package consts

type Country struct {
	Name  string `json:"name"`
	Iso2  string `json:"iso2"`
	Iso3  string `json:"iso3"`
	Emoji string `json:"emoji"`
}

var Countries = []Country{
	{"Afghanistan", "AF", "AFG", "🇦🇫"},
	{"Aland Islands", "AX", "ALA", "🇦🇽"},
	{"Albania", "AL", "ALB", "🇦🇱"},
	{"Algeria", "DZ", "DZA", "🇩🇿"},
	{"American Samoa", "AS", "ASM", "🇦🇸"},
	{"Andorra", "AD", "AND", "🇦🇩"},
	{"Angola", "AO", "AGO", "🇦🇴"},
	{"Anguilla", "AI", "AIA", "🇦🇮"},
	{"Antarctica", "AQ", "ATA", "🇦🇶"},
	{"Antigua And Barbuda", "AG", "ATG", "🇦🇬"},
	{"Argentina", "AR", "ARG", "🇦🇷"},
	{"Armenia", "AM", "ARM", "🇦🇲"},
	{"Aruba", "AW", "ABW", "🇦🇼"},
	{"Australia", "AU", "AUS", "🇦🇺"},
	{"Austria", "AT", "AUT", "🇦🇹"},
	{"Azerbaijan", "AZ", "AZE", "🇦🇿"},
	{"Bahrain", "BH", "BHR", "🇧🇭"},
	{"Bangladesh", "BD", "BGD", "🇧🇩"},
	{"Barbados", "BB", "BRB", "🇧🇧"},
	{"Belarus", "BY", "BLR", "🇧🇾"},
	{"Belgium", "BE", "BEL", "🇧🇪"},
	{"Belize", "BZ", "BLZ", "🇧🇿"},
	{"Benin", "BJ", "BEN", "🇧🇯"},
	{"Bermuda", "BM", "BMU", "🇧🇲"},
	{"Bhutan", "BT", "BTN", "🇧🇹"},
	{"Bolivia", "BO", "BOL", "🇧🇴"},
	{"Bonaire, Sint Eustatius and Saba", "BQ", "BES", "🇧🇶"},
	{"Bosnia and Herzegovina", "BA", "BIH", "🇧🇦"},
	{"Botswana", "BW", "BWA", "🇧🇼"},
	{"Bouvet Island", "BV", "BVT", "🇧🇻"},
	{"Brazil", "BR", "BRA", "🇧🇷"},
	{"British Indian Ocean Territory", "IO", "IOT", "🇮🇴"},
	{"Brunei", "BN", "BRN", "🇧🇳"},
	{"Bulgaria", "BG", "BGR", "🇧🇬"},
	{"Burkina Faso", "BF", "BFA", "🇧🇫"},
	{"Burundi", "BI", "BDI", "🇧🇮"},
	{"Cambodia", "KH", "KHM", "🇰🇭"},
	{"Cameroon", "CM", "CMR", "🇨🇲"},
	{"Canada", "CA", "CAN", "🇨🇦"},
	{"Cape Verde", "CV", "CPV", "🇨🇻"},
	{"Cayman Islands", "KY", "CYM", "🇰🇾"},
	{"Central African Republic", "CF", "CAF", "🇨🇫"},
	{"Chad", "TD", "TCD", "🇹🇩"},
	{"Chile", "CL", "CHL", "🇨🇱"},
	{"China", "CN", "CHN", "🇨🇳"},
	{"Christmas Island", "CX", "CXR", "🇨🇽"},
	{"Cocos (Keeling) Islands", "CC", "CCK", "🇨🇨"},
	{"Colombia", "CO", "COL", "🇨🇴"},
	{"Comoros", "KM", "COM", "🇰🇲"},
	{"Congo", "CG", "COG", "🇨🇬"},
	{"Cook Islands", "CK", "COK", "🇨🇰"},
	{"Costa Rica", "CR", "CRI", "🇨🇷"},
	{"Cote D'Ivoire (Ivory Coast)", "CI", "CIV", "🇨🇮"},
	{"Croatia", "HR", "HRV", "🇭🇷"},
	{"Cuba", "CU", "CUB", "🇨🇺"},
	{"Curaçao", "CW", "CUW", "🇨🇼"},
	{"Cyprus", "CY", "CYP", "🇨🇾"},
	{"Czech Republic", "CZ", "CZE", "🇨🇿"},
	{"Democratic Republic of the Congo", "CD", "COD", "🇨🇩"},
	{"Denmark", "DK", "DNK", "🇩🇰"},
	{"Djibouti", "DJ", "DJI", "🇩🇯"},
	{"Dominica", "DM", "DMA", "🇩🇲"},
	{"Dominican Republic", "DO", "DOM", "🇩🇴"},
	{"East Timor", "TL", "TLS", "🇹🇱"},
	{"Ecuador", "EC", "ECU", "🇪🇨"},
	{"Egypt", "EG", "EGY", "🇪🇬"},
	{"El Salvador", "SV", "SLV", "🇸🇻"},
	{"Equatorial Guinea", "GQ", "GNQ", "🇬🇶"},
	{"Eritrea", "ER", "ERI", "🇪🇷"},
	{"Estonia", "EE", "EST", "🇪🇪"},
	{"Ethiopia", "ET", "ETH", "🇪🇹"},
	{"Falkland Islands", "FK", "FLK", "🇫🇰"},
	{"Faroe Islands", "FO", "FRO", "🇫🇴"},
	{"Fiji Islands", "FJ", "FJI", "🇫🇯"},
	{"Finland", "FI", "FIN", "🇫🇮"},
	{"France", "FR", "FRA", "🇫🇷"},
	{"French Guiana", "GF", "GUF", "🇬🇫"},
	{"French Polynesia", "PF", "PYF", "🇵🇫"},
	{"French Southern Territories", "TF", "ATF", "🇹🇫"},
	{"Gabon", "GA", "GAB", "🇬🇦"},
	{"Gambia The", "GM", "GMB", "🇬🇲"},
	{"Georgia", "GE", "GEO", "🇬🇪"},
	{"Germany", "DE", "DEU", "🇩🇪"},
	{"Ghana", "GH", "GHA", "🇬🇭"},
	{"Gibraltar", "GI", "GIB", "🇬🇮"},
	{"Greece", "GR", "GRC", "🇬🇷"},
	{"Greenland", "GL", "GRL", "🇬🇱"},
	{"Grenada", "GD", "GRD", "🇬🇩"},
	{"Guadeloupe", "GP", "GLP", "🇬🇵"},
	{"Guam", "GU", "GUM", "🇬🇺"},
	{"Guatemala", "GT", "GTM", "🇬🇹"},
	{"Guernsey and Alderney", "GG", "GGY", "🇬🇬"},
	{"Guinea", "GN", "GIN", "🇬🇳"},
	{"Guinea-Bissau", "GW", "GNB", "🇬🇼"},
	{"Guyana", "GY", "GUY", "🇬🇾"},
	{"Haiti", "HT", "HTI", "🇭🇹"},
	{"Heard Island and McDonald Islands", "HM", "HMD", "🇭🇲"},
	{"Honduras", "HN", "HND", "🇭🇳"},
	{"Hong Kong S.A.R.", "HK", "HKG", "🇭🇰"},
	{"Hungary", "HU", "HUN", "🇭🇺"},
	{"Iceland", "IS", "ISL", "🇮🇸"},
	{"India", "IN", "IND", "🇮🇳"},
	{"Indonesia", "ID", "IDN", "🇮🇩"},
	{"Iran", "IR", "IRN", "🇮🇷"},
	{"Iraq", "IQ", "IRQ", "🇮🇶"},
	{"Ireland", "IE", "IRL", "🇮🇪"},
	{"Israel", "IL", "ISR", "🇮🇱"},
	{"Italy", "IT", "ITA", "🇮🇹"},
	{"Jamaica", "JM", "JAM", "🇯🇲"},
	{"Japan", "JP", "JPN", "🇯🇵"},
	{"Jersey", "JE", "JEY", "🇯🇪"},
	{"Jordan", "JO", "JOR", "🇯🇴"},
	{"Kazakhstan", "KZ", "KAZ", "🇰🇿"},
	{"Kenya", "KE", "KEN", "🇰🇪"},
	{"Kiribati", "KI", "KIR", "🇰🇮"},
	{"Kosovo", "XK", "XKX", "🇽🇰"},
	{"Kuwait", "KW", "KWT", "🇰🇼"},
	{"Kyrgyzstan", "KG", "KGZ", "🇰🇬"},
	{"Laos", "LA", "LAO", "🇱🇦"},
	{"Latvia", "LV", "LVA", "🇱🇻"},
	{"Lebanon", "LB", "LBN", "🇱🇧"},
	{"Lesotho", "LS", "LSO", "🇱🇸"},
	{"Liberia", "LR", "LBR", "🇱🇷"},
	{"Libya", "LY", "LBY", "🇱🇾"},
	{"Liechtenstein", "LI", "LIE", "🇱🇮"},
	{"Lithuania", "LT", "LTU", "🇱🇹"},
	{"Luxembourg", "LU", "LUX", "🇱🇺"},
	{"Macau S.A.R.", "MO", "MAC", "🇲🇴"},
	{"Madagascar", "MG", "MDG", "🇲🇬"},
	{"Malawi", "MW", "MWI", "🇲🇼"},
	{"Malaysia", "MY", "MYS", "🇲🇾"},
	{"Maldives", "MV", "MDV", "🇲🇻"},
	{"Mali", "ML", "MLI", "🇲🇱"},
	{"Malta", "MT", "MLT", "🇲🇹"},
	{"Man (Isle of)", "IM", "IMN", "🇮🇲"},
	{"Marshall Islands", "MH", "MHL", "🇲🇭"},
	{"Martinique", "MQ", "MTQ", "🇲🇶"},
	{"Mauritania", "MR", "MRT", "🇲🇷"},
	{"Mauritius", "MU", "MUS", "🇲🇺"},
	{"Mayotte", "YT", "MYT", "🇾🇹"},
	{"Mexico", "MX", "MEX", "🇲🇽"},
	{"Micronesia", "FM", "FSM", "🇫🇲"},
	{"Moldova", "MD", "MDA", "🇲🇩"},
	{"Monaco", "MC", "MCO", "🇲🇨"},
	{"Mongolia", "MN", "MNG", "🇲🇳"},
	{"Montenegro", "ME", "MNE", "🇲🇪"},
	{"Montserrat", "MS", "MSR", "🇲🇸"},
	{"Morocco", "MA", "MAR", "🇲🇦"},
	{"Mozambique", "MZ", "MOZ", "🇲🇿"},
	{"Myanmar", "MM", "MMR", "🇲🇲"},
	{"Namibia", "NA", "NAM", "🇳🇦"},
	{"Nauru", "NR", "NRU", "🇳🇷"},
	{"Nepal", "NP", "NPL", "🇳🇵"},
	{"Netherlands", "NL", "NLD", "🇳🇱"},
	{"New Caledonia", "NC", "NCL", "🇳🇨"},
	{"New Zealand", "NZ", "NZL", "🇳🇿"},
	{"Nicaragua", "NI", "NIC", "🇳🇮"},
	{"Niger", "NE", "NER", "🇳🇪"},
	{"Nigeria", "NG", "NGA", "🇳🇬"},
	{"Niue", "NU", "NIU", "🇳🇺"},
	{"Norfolk Island", "NF", "NFK", "🇳🇫"},
	{"North Korea", "KP", "PRK", "🇰🇵"},
	{"North Macedonia", "MK", "MKD", "🇲🇰"},
	{"Northern Mariana Islands", "MP", "MNP", "🇲🇵"},
	{"Norway", "NO", "NOR", "🇳🇴"},
	{"Oman", "OM", "OMN", "🇴🇲"},
	{"Pakistan", "PK", "PAK", "🇵🇰"},
	{"Palau", "PW", "PLW", "🇵🇼"},
	{"Palestinian Territory Occupied", "PS", "PSE", "🇵🇸"},
	{"Panama", "PA", "PAN", "🇵🇦"},
	{"Papua new Guinea", "PG", "PNG", "🇵🇬"},
	{"Paraguay", "PY", "PRY", "🇵🇾"},
	{"Peru", "PE", "PER", "🇵🇪"},
	{"Philippines", "PH", "PHL", "🇵🇭"},
	{"Pitcairn Island", "PN", "PCN", "🇵🇳"},
	{"Poland", "PL", "POL", "🇵🇱"},
	{"Portugal", "PT", "PRT", "🇵🇹"},
	{"Puerto Rico", "PR", "PRI", "🇵🇷"},
	{"Qatar", "QA", "QAT", "🇶🇦"},
	{"Reunion", "RE", "REU", "🇷🇪"},
	{"Romania", "RO", "ROU", "🇷🇴"},
	{"Russia", "RU", "RUS", "🇷🇺"},
	{"Rwanda", "RW", "RWA", "🇷🇼"},
	{"Saint Helena", "SH", "SHN", "🇸🇭"},
	{"Saint Kitts And Nevis", "KN", "KNA", "🇰🇳"},
	{"Saint Lucia", "LC", "LCA", "🇱🇨"},
	{"Saint Pierre and Miquelon", "PM", "SPM", "🇵🇲"},
	{"Saint Vincent And The Grenadines", "VC", "VCT", "🇻🇨"},
	{"Saint-Barthelemy", "BL", "BLM", "🇧🇱"},
	{"Saint-Martin (French part)", "MF", "MAF", "🇲🇫"},
	{"Samoa", "WS", "WSM", "🇼🇸"},
	{"San Marino", "SM", "SMR", "🇸🇲"},
	{"Sao Tome and Principe", "ST", "STP", "🇸🇹"},
	{"Saudi Arabia", "SA", "SAU", "🇸🇦"},
	{"Senegal", "SN", "SEN", "🇸🇳"},
	{"Serbia", "RS", "SRB", "🇷🇸"},
	{"Seychelles", "SC", "SYC", "🇸🇨"},
	{"Sierra Leone", "SL", "SLE", "🇸🇱"},
	{"Singapore", "SG", "SGP", "🇸🇬"},
	{"Sint Maarten (Dutch part)", "SX", "SXM", "🇸🇽"},
	{"Slovakia", "SK", "SVK", "🇸🇰"},
	{"Slovenia", "SI", "SVN", "🇸🇮"},
	{"Solomon Islands", "SB", "SLB", "🇸🇧"},
	{"Somalia", "SO", "SOM", "🇸🇴"},
	{"South Africa", "ZA", "ZAF", "🇿🇦"},
	{"South Georgia", "GS", "SGS", "🇬🇸"},
	{"South Korea", "KR", "KOR", "🇰🇷"},
	{"South Sudan", "SS", "SSD", "🇸🇸"},
	{"Spain", "ES", "ESP", "🇪🇸"},
	{"Sri Lanka", "LK", "LKA", "🇱🇰"},
	{"Sudan", "SD", "SDN", "🇸🇩"},
	{"Suriname", "SR", "SUR", "🇸🇷"},
	{"Svalbard And Jan Mayen Islands", "SJ", "SJM", "🇸🇯"},
	{"Swaziland", "SZ", "SWZ", "🇸🇿"},
	{"Sweden", "SE", "SWE", "🇸🇪"},
	{"Switzerland", "CH", "CHE", "🇨🇭"},
	{"Syria", "SY", "SYR", "🇸🇾"},
	{"Taiwan", "TW", "TWN", "🇹🇼"},
	{"Tajikistan", "TJ", "TJK", "🇹🇯"},
	{"Tanzania", "TZ", "TZA", "🇹🇿"},
	{"Thailand", "TH", "THA", "🇹🇭"},
	{"The Bahamas", "BS", "BHS", "🇧🇸"},
	{"Togo", "TG", "TGO", "🇹🇬"},
	{"Tokelau", "TK", "TKL", "🇹🇰"},
	{"Tonga", "TO", "TON", "🇹🇴"},
	{"Trinidad And Tobago", "TT", "TTO", "🇹🇹"},
	{"Tunisia", "TN", "TUN", "🇹🇳"},
	{"Turkey", "TR", "TUR", "🇹🇷"},
	{"Turkmenistan", "TM", "TKM", "🇹🇲"},
	{"Turks And Caicos Islands", "TC", "TCA", "🇹🇨"},
	{"Tuvalu", "TV", "TUV", "🇹🇻"},
	{"Uganda", "UG", "UGA", "🇺🇬"},
	{"Ukraine", "UA", "UKR", "🇺🇦"},
	{"United Arab Emirates", "AE", "ARE", "🇦🇪"},
	{"United Kingdom", "GB", "GBR", "🇬🇧"},
	{"United States", "US", "USA", "🇺🇸"},
	{"United States Minor Outlying Islands", "UM", "UMI", "🇺🇲"},
	{"Uruguay", "UY", "URY", "🇺🇾"},
	{"Uzbekistan", "UZ", "UZB", "🇺🇿"},
	{"Vanuatu", "VU", "VUT", "🇻🇺"},
	{"Vatican City State (Holy See)", "VA", "VAT", "🇻🇦"},
	{"Venezuela", "VE", "VEN", "🇻🇪"},
	{"Vietnam", "VN", "VNM", "🇻🇳"},
	{"Virgin Islands (British)", "VG", "VGB", "🇻🇬"},
	{"Virgin Islands (US)", "VI", "VIR", "🇻🇮"},
	{"Wallis And Futuna Islands", "WF", "WLF", "🇼🇫"},
	{"Western Sahara", "EH", "ESH", "🇪🇭"},
	{"Yemen", "YE", "YEM", "🇾🇪"},
	{"Zambia", "ZM", "ZMB", "🇿🇲"},
	{"Zimbabwe", "ZW", "ZWE", "🇿🇼"},
}
