// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/api/challenges": {
            "patch": {
                "description": "Requires **Author** privileges or higher.\nUpdates an existing challenge with the provided fields, only the ` + "`" + `chall_id` + "`" + ` is required.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "challenges"
                ],
                "summary": "[Author+] Updates details of an existing challenge",
                "parameters": [
                    {
                        "description": "` + "`" + `chall_id` + "`" + ` is required, the rest of the fields are optional, only provide the fields you want to update",
                        "name": "challenge",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/challenges_update.UpdateChallParams"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK"
                    },
                    "400": {
                        "description": "Possible errors: ` + "`" + `Invalid JSON format` + "`" + ` | ` + "`" + `Missing required fields` + "`" + ` | ` + "`" + `No data provided to update` + "`" + ` | ` + "`" + `Name must not exceed 128` + "`" + ` | ` + "`" + `Category must not exceed 32` + "`" + ` | ` + "`" + `Description must not exceed 10240` + "`" + ` | ` + "`" + `Authors[i] must not exceed 64` + "`" + ` | ` + "`" + `Tags[i] must not exceed 32` + "`" + ` | ` + "`" + `Type must be one of: Normal Container Compose` + "`" + ` | ` + "`" + `MaxPoints must be at least 0` + "`" + ` | ` + "`" + `ScoreType must be one of: Static Dynamic` + "`" + ` | ` + "`" + `Port must be at least 0` + "`" + ` | ` + "`" + `Port must not exceed 65535` + "`" + ` | ` + "`" + `ConnType must be one of: NONE TCP HTTP HTTPS` + "`" + ` | ` + "`" + `Lifetime must be at least 0` + "`" + ` | ` + "`" + `Invalid environment variables` + "`" + ` | ` + "`" + `MaxMemory must be at least 0` + "`" + ` | ` + "`" + `Invalid Max CPU, must be a positive 32-bit integer` + "`" + ` | ` + "`" + `ChallID must be at least 0` + "`" + `",
                        "schema": {
                            "$ref": "#/definitions/models.Error"
                        }
                    },
                    "404": {
                        "description": "Possible errors: ` + "`" + `Challenge not found` + "`" + ` | ` + "`" + `Category not found` + "`" + `",
                        "schema": {
                            "$ref": "#/definitions/models.Error"
                        }
                    },
                    "409": {
                        "description": "Possible errors: ` + "`" + `Challenge name already exists` + "`" + `",
                        "schema": {
                            "$ref": "#/definitions/models.Error"
                        }
                    },
                    "500": {
                        "description": "Possible errors: ` + "`" + `Error fetching challenge` + "`" + ` | ` + "`" + `Error updating challenge` + "`" + ` | ` + "`" + `Internal server error` + "`" + `",
                        "schema": {
                            "$ref": "#/definitions/models.Error"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "challenges_update.UpdateChallParams": {
            "type": "object",
            "required": [
                "chall_id"
            ],
            "properties": {
                "authors": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "category": {
                    "type": "string"
                },
                "chall_id": {
                    "type": "integer"
                },
                "compose": {
                    "type": "string"
                },
                "conn_type": {
                    "$ref": "#/definitions/sqlc.ConnType"
                },
                "description": {
                    "type": "string"
                },
                "envs": {
                    "type": "string"
                },
                "hash_domain": {
                    "type": "boolean"
                },
                "hidden": {
                    "type": "boolean"
                },
                "host": {
                    "type": "string"
                },
                "image": {
                    "type": "string"
                },
                "lifetime": {
                    "type": "integer"
                },
                "max_cpu": {
                    "type": "string"
                },
                "max_memory": {
                    "type": "integer"
                },
                "max_points": {
                    "type": "integer"
                },
                "name": {
                    "type": "string"
                },
                "port": {
                    "type": "integer"
                },
                "renewable": {
                    "type": "boolean"
                },
                "score_type": {
                    "$ref": "#/definitions/sqlc.ScoreType"
                },
                "tags": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "type": {
                    "$ref": "#/definitions/sqlc.DeployType"
                }
            }
        },
        "models.Error": {
            "type": "object",
            "properties": {
                "error": {
                    "type": "string"
                }
            }
        },
        "sqlc.ConnType": {
            "type": "string",
            "enum": [
                "NONE",
                "TCP",
                "HTTP",
                "HTTPS"
            ],
            "x-enum-varnames": [
                "ConnTypeNONE",
                "ConnTypeTCP",
                "ConnTypeHTTP",
                "ConnTypeHTTPS"
            ]
        },
        "sqlc.DeployType": {
            "type": "string",
            "enum": [
                "Normal",
                "Container",
                "Compose"
            ],
            "x-enum-varnames": [
                "DeployTypeNormal",
                "DeployTypeContainer",
                "DeployTypeCompose"
            ]
        },
        "sqlc.ScoreType": {
            "type": "string",
            "enum": [
                "Static",
                "Dynamic"
            ],
            "x-enum-varnames": [
                "ScoreTypeStatic",
                "ScoreTypeDynamic"
            ]
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "",
	Host:             "",
	BasePath:         "/",
	Schemes:          []string{},
	Title:            "TRXd API",
	Description:      "",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
