basePath: /
definitions:
  attachments_create.Data:
    properties:
      chall_id:
        type: integer
    required:
    - chall_id
    type: object
  attachments_delete.Data:
    properties:
      chall_id:
        type: integer
      names:
        items:
          type: string
        type: array
    required:
    - chall_id
    - names
    type: object
  categories_create.Data:
    properties:
      name:
        type: string
    required:
    - name
    type: object
  categories_delete.Data:
    properties:
      name:
        type: string
    required:
    - name
    type: object
  categories_update.Data:
    properties:
      name:
        type: string
      new_name:
        type: string
    required:
    - name
    - new_name
    type: object
  challenges_update.UpdateChallParams:
    properties:
      authors:
        items:
          type: string
        type: array
      category:
        type: string
      chall_id:
        type: integer
      compose:
        type: string
      conn_type:
        $ref: '#/definitions/sqlc.ConnType'
      description:
        type: string
      envs:
        type: string
      hash_domain:
        type: boolean
      hidden:
        type: boolean
      host:
        type: string
      image:
        type: string
      lifetime:
        type: integer
      max_cpu:
        type: string
      max_memory:
        type: integer
      max_points:
        type: integer
      name:
        type: string
      port:
        type: integer
      renewable:
        type: boolean
      score_type:
        $ref: '#/definitions/sqlc.ScoreType'
      tags:
        items:
          type: string
        type: array
      type:
        $ref: '#/definitions/sqlc.DeployType'
    required:
    - chall_id
    type: object
  models.Error:
    properties:
      error:
        type: string
    type: object
  sqlc.ConnType:
    enum:
    - NONE
    - TCP
    - HTTP
    - HTTPS
    type: string
    x-enum-varnames:
    - ConnTypeNONE
    - ConnTypeTCP
    - ConnTypeHTTP
    - ConnTypeHTTPS
  sqlc.DeployType:
    enum:
    - Normal
    - Container
    - Compose
    type: string
    x-enum-varnames:
    - DeployTypeNormal
    - DeployTypeContainer
    - DeployTypeCompose
  sqlc.ScoreType:
    enum:
    - Static
    - Dynamic
    type: string
    x-enum-varnames:
    - ScoreTypeStatic
    - ScoreTypeDynamic
info:
  contact: {}
  title: TRXd API
paths:
  /api/attachments:
    delete:
      consumes:
      - application/json
      description: |-
        Requires **Author** privileges or higher.
        Deletes attachments for an existing challenge with the provided names.
      parameters:
      - description: all fields are required
        in: body
        name: data
        required: true
        schema:
          $ref: '#/definitions/attachments_delete.Data'
      produces:
      - application/json
      responses:
        "200":
          description: OK
        "400":
          description: 'Possible errors: `Invalid JSON format` | `Missing required
            fields` | `ChallID must be at least 0` | `Names[i] must not exceed 128`'
          schema:
            $ref: '#/definitions/models.Error'
        "404":
          description: 'Possible errors: `Attachment not found`'
          schema:
            $ref: '#/definitions/models.Error'
        "500":
          description: 'Possible errors: `Error fetching attachment` | `Error deleting
            attachment` | `Internal server error`'
          schema:
            $ref: '#/definitions/models.Error'
      summary: '[Author+] Deletes attachments for a challenge'
      tags:
      - attachments
    post:
      consumes:
      - multipart/form-data
      description: |-
        Requires **Author** privileges or higher.
        Creates new attachments for an existing challenge with the provided files.
      parameters:
      - description: all fields are required
        in: body
        name: data
        required: true
        schema:
          $ref: '#/definitions/attachments_create.Data'
      - collectionFormat: csv
        description: the list of files to upload (at least one file is required)
        in: formData
        items:
          type: file
        name: files
        required: true
        type: array
      produces:
      - application/json
      responses:
        "200":
          description: OK
        "400":
          description: 'Possible errors: `Invalid multipart form` | `Invalid form
            data` | `Missing required fields` | `ChallID must be at least 0` | `Attachments[i]
            must not exceed 128`'
          schema:
            $ref: '#/definitions/models.Error'
        "404":
          description: 'Possible errors: `Challenge not found`'
          schema:
            $ref: '#/definitions/models.Error'
        "409":
          description: 'Possible errors: `Attachment already exists`'
          schema:
            $ref: '#/definitions/models.Error'
        "500":
          description: 'Possible errors: `Error fetching challenge` | `Error creating
            attachments` | `Internal server error`'
          schema:
            $ref: '#/definitions/models.Error'
      summary: '[Author+] Creates new attachments for a challenge'
      tags:
      - attachments
  /api/categories:
    delete:
      consumes:
      - application/json
      description: |-
        Requires **Author** privileges or higher.
        Deletes an existing category with the provided name.
      parameters:
      - description: all fields are required
        in: body
        name: data
        required: true
        schema:
          $ref: '#/definitions/categories_delete.Data'
      produces:
      - application/json
      responses:
        "200":
          description: OK
        "400":
          description: 'Possible errors: `Invalid JSON format` | `Missing required
            fields` | `Name must not exceed 32`'
          schema:
            $ref: '#/definitions/models.Error'
        "500":
          description: 'Possible errors: `Error deleting category` | `Internal server
            error`'
          schema:
            $ref: '#/definitions/models.Error'
      summary: '[Author+] Deletes a category'
      tags:
      - categories
    get:
      description: |-
        Requires **Player** privileges or higher (with role **Player** is also required to be in a team and the competition has to be active).
        Retrieves a list of all categories (with role **Player** only visible one are returned).
      produces:
      - application/json
      responses:
        "200":
          description: List of category names
          schema:
            items:
              type: string
            type: array
        "500":
          description: 'Possible errors: `Error fetching categories` | `Internal server
            error`'
          schema:
            $ref: '#/definitions/models.Error'
      summary: '[Player+] Gets all categories'
      tags:
      - categories
    patch:
      consumes:
      - application/json
      description: |-
        Requires **Author** privileges or higher.
        Updates an existing category with the provided name (also updates its own challenges categories).
      parameters:
      - description: all fields are required
        in: body
        name: data
        required: true
        schema:
          $ref: '#/definitions/categories_update.Data'
      produces:
      - application/json
      responses:
        "200":
          description: OK
        "400":
          description: 'Possible errors: `Invalid JSON format` | `Missing required
            fields` | `Name must not exceed 32` | `NewName must not exceed 32`'
          schema:
            $ref: '#/definitions/models.Error'
        "404":
          description: 'Possible errors: `Category not found`'
          schema:
            $ref: '#/definitions/models.Error'
        "409":
          description: 'Possible errors: `Category already exists`'
          schema:
            $ref: '#/definitions/models.Error'
        "500":
          description: 'Possible errors: `Error fetching category` | `Error creating
            category` | `Error updating category` | `Error deleting category` | `Internal
            server error`'
          schema:
            $ref: '#/definitions/models.Error'
      summary: '[Author+] Updates a category'
      tags:
      - categories
    post:
      consumes:
      - application/json
      description: |-
        Requires **Author** privileges or higher.
        Creates a new category with the provided name.
      parameters:
      - description: all fields are required
        in: body
        name: data
        required: true
        schema:
          $ref: '#/definitions/categories_create.Data'
      produces:
      - application/json
      responses:
        "200":
          description: OK
        "400":
          description: 'Possible errors: `Invalid JSON format` | `Missing required
            fields` | `Name must not exceed 32`'
          schema:
            $ref: '#/definitions/models.Error'
        "409":
          description: 'Possible errors: `Category already exists`'
          schema:
            $ref: '#/definitions/models.Error'
        "500":
          description: 'Possible errors: `Error creating category` | `Internal server
            error`'
          schema:
            $ref: '#/definitions/models.Error'
      summary: '[Author+] Creates a new category'
      tags:
      - categories
  /api/challenges:
    patch:
      consumes:
      - application/json
      description: |-
        Requires **Author** privileges or higher.
        Updates an existing challenge with the provided fields, only the `chall_id` is required.
      parameters:
      - description: '`chall_id` is required, the rest of the fields are optional,
          only provide the fields you want to update'
        in: body
        name: data
        required: true
        schema:
          $ref: '#/definitions/challenges_update.UpdateChallParams'
      produces:
      - application/json
      responses:
        "200":
          description: OK
        "400":
          description: 'Possible errors: `Invalid JSON format` | `Missing required
            fields` | `No data provided to update` | `Name must not exceed 128` |
            `Category must not exceed 32` | `Description must not exceed 10240` |
            `Authors[i] must not exceed 64` | `Tags[i] must not exceed 32` | `Type
            must be one of: Normal Container Compose` | `MaxPoints must be at least
            0` | `ScoreType must be one of: Static Dynamic` | `Port must be at least
            0` | `Port must not exceed 65535` | `ConnType must be one of: NONE TCP
            HTTP HTTPS` | `Lifetime must be at least 0` | `Invalid environment variables`
            | `MaxMemory must be at least 0` | `Invalid Max CPU, must be a positive
            32-bit integer` | `ChallID must be at least 0`'
          schema:
            $ref: '#/definitions/models.Error'
        "404":
          description: 'Possible errors: `Challenge not found` | `Category not found`'
          schema:
            $ref: '#/definitions/models.Error'
        "409":
          description: 'Possible errors: `Challenge name already exists`'
          schema:
            $ref: '#/definitions/models.Error'
        "500":
          description: 'Possible errors: `Error fetching challenge` | `Error updating
            challenge` | `Internal server error`'
          schema:
            $ref: '#/definitions/models.Error'
      summary: '[Author+] Updates details of an existing challenge'
      tags:
      - challenges
swagger: "2.0"
