// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: challenges.sql

package sqlc

import (
	"context"

	"github.com/lib/pq"
)

const getChallengeByID = `-- name: GetChallengeByID :one
SELECT
  id,
  name,
  category,
  description,
  authors,
  tags,
  instance_type,
  hidden,

  max_points,
  score_type,
  points,
  solves,

  host,
  port,
  conn_type,
  hash_domain,

  image,
  compose,
  COALESCE(NULLIF(lifetime, 0), (SELECT value::INTEGER FROM configs WHERE key='instance-lifetime'))::INTEGER AS lifetime,
  renewable,
  envs,
  COALESCE(NULLIF(max_memory, 0), (SELECT value::INTEGER FROM configs WHERE key='instance-max-memory'))::INTEGER AS max_memory,
  COALESCE(NULLIF(max_cpu, ''), (SELECT value FROM configs WHERE key='instance-max-cpu'))::TEXT AS max_cpu
FROM challenges
WHERE id = $1
`

type GetChallengeByIDRow struct {
	ID           int32        `json:"id"`
	Name         string       `json:"name"`
	Category     string       `json:"category"`
	Description  string       `json:"description"`
	Authors      []string     `json:"authors"`
	Tags         []string     `json:"tags"`
	InstanceType InstanceType `json:"instance_type"`
	Hidden       bool         `json:"hidden"`
	MaxPoints    int32        `json:"max_points"`
	ScoreType    ScoreType    `json:"score_type"`
	Points       int32        `json:"points"`
	Solves       int32        `json:"solves"`
	Host         string       `json:"host"`
	Port         int32        `json:"port"`
	ConnType     ConnType     `json:"conn_type"`
	HashDomain   bool         `json:"hash_domain"`
	Image        string       `json:"image"`
	Compose      string       `json:"compose"`
	Lifetime     int32        `json:"lifetime"`
	Renewable    bool         `json:"renewable"`
	Envs         string       `json:"envs"`
	MaxMemory    int32        `json:"max_memory"`
	MaxCpu       string       `json:"max_cpu"`
}

// Retrieve a challenge by its ID
func (q *Queries) GetChallengeByID(ctx context.Context, id int32) (GetChallengeByIDRow, error) {
	row := q.queryRow(ctx, q.getChallengeByIDStmt, getChallengeByID, id)
	var i GetChallengeByIDRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Category,
		&i.Description,
		pq.Array(&i.Authors),
		pq.Array(&i.Tags),
		&i.InstanceType,
		&i.Hidden,
		&i.MaxPoints,
		&i.ScoreType,
		&i.Points,
		&i.Solves,
		&i.Host,
		&i.Port,
		&i.ConnType,
		&i.HashDomain,
		&i.Image,
		&i.Compose,
		&i.Lifetime,
		&i.Renewable,
		&i.Envs,
		&i.MaxMemory,
		&i.MaxCpu,
	)
	return i, err
}

const getHiddenAndAttachments = `-- name: GetHiddenAndAttachments :one
SELECT
  c.hidden, 
  (ARRAY_AGG(a.hash || '/' || a.name) FILTER (WHERE a.name IS NOT NULL))::TEXT[] AS attachments
FROM challenges c
LEFT JOIN attachments a
  ON a.chall_id = c.id
WHERE c.id = $1
GROUP BY c.hidden
`

type GetHiddenAndAttachmentsRow struct {
	Hidden      bool     `json:"hidden"`
	Attachments []string `json:"attachments"`
}

// Checks if a challenge is hidden
func (q *Queries) GetHiddenAndAttachments(ctx context.Context, id int32) (GetHiddenAndAttachmentsRow, error) {
	row := q.queryRow(ctx, q.getHiddenAndAttachmentsStmt, getHiddenAndAttachments, id)
	var i GetHiddenAndAttachmentsRow
	err := row.Scan(&i.Hidden, pq.Array(&i.Attachments))
	return i, err
}

const getTotalCategoryChallenges = `-- name: GetTotalCategoryChallenges :many
SELECT category, COUNT(*)
FROM challenges
WHERE hidden = FALSE
GROUP BY category
ORDER BY category ASC
`

type GetTotalCategoryChallengesRow struct {
	Category string `json:"category"`
	Count    int64  `json:"count"`
}

// Retrieve the total number of challenges for each category
func (q *Queries) GetTotalCategoryChallenges(ctx context.Context) ([]GetTotalCategoryChallengesRow, error) {
	rows, err := q.query(ctx, q.getTotalCategoryChallengesStmt, getTotalCategoryChallenges)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetTotalCategoryChallengesRow
	for rows.Next() {
		var i GetTotalCategoryChallengesRow
		if err := rows.Scan(&i.Category, &i.Count); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
