// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlc

import (
	"context"
	"database/sql"
	"fmt"
)

type DBTX interface {
	ExecContext(context.Context, string, ...interface{}) (sql.Result, error)
	PrepareContext(context.Context, string) (*sql.Stmt, error)
	QueryContext(context.Context, string, ...interface{}) (*sql.Rows, error)
	QueryRowContext(context.Context, string, ...interface{}) *sql.Row
}

func New(db DBTX) *Queries {
	return &Queries{db: db}
}

func Prepare(ctx context.Context, db DBTX) (*Queries, error) {
	q := Queries{db: db}
	var err error
	if q.addTeamMemberStmt, err = db.PrepareContext(ctx, addTeamMember); err != nil {
		return nil, fmt.Errorf("error preparing query AddTeamMember: %w", err)
	}
	if q.changeUserRoleStmt, err = db.PrepareContext(ctx, changeUserRole); err != nil {
		return nil, fmt.Errorf("error preparing query ChangeUserRole: %w", err)
	}
	if q.checkFlagsStmt, err = db.PrepareContext(ctx, checkFlags); err != nil {
		return nil, fmt.Errorf("error preparing query CheckFlags: %w", err)
	}
	if q.createAttachmentStmt, err = db.PrepareContext(ctx, createAttachment); err != nil {
		return nil, fmt.Errorf("error preparing query CreateAttachment: %w", err)
	}
	if q.createCategoryStmt, err = db.PrepareContext(ctx, createCategory); err != nil {
		return nil, fmt.Errorf("error preparing query CreateCategory: %w", err)
	}
	if q.createChallengeStmt, err = db.PrepareContext(ctx, createChallenge); err != nil {
		return nil, fmt.Errorf("error preparing query CreateChallenge: %w", err)
	}
	if q.createConfigStmt, err = db.PrepareContext(ctx, createConfig); err != nil {
		return nil, fmt.Errorf("error preparing query CreateConfig: %w", err)
	}
	if q.createFlagStmt, err = db.PrepareContext(ctx, createFlag); err != nil {
		return nil, fmt.Errorf("error preparing query CreateFlag: %w", err)
	}
	if q.createInstanceStmt, err = db.PrepareContext(ctx, createInstance); err != nil {
		return nil, fmt.Errorf("error preparing query CreateInstance: %w", err)
	}
	if q.deleteAttachmentStmt, err = db.PrepareContext(ctx, deleteAttachment); err != nil {
		return nil, fmt.Errorf("error preparing query DeleteAttachment: %w", err)
	}
	if q.deleteCategoryStmt, err = db.PrepareContext(ctx, deleteCategory); err != nil {
		return nil, fmt.Errorf("error preparing query DeleteCategory: %w", err)
	}
	if q.deleteChallengeStmt, err = db.PrepareContext(ctx, deleteChallenge); err != nil {
		return nil, fmt.Errorf("error preparing query DeleteChallenge: %w", err)
	}
	if q.deleteFlagStmt, err = db.PrepareContext(ctx, deleteFlag); err != nil {
		return nil, fmt.Errorf("error preparing query DeleteFlag: %w", err)
	}
	if q.deleteInstanceStmt, err = db.PrepareContext(ctx, deleteInstance); err != nil {
		return nil, fmt.Errorf("error preparing query DeleteInstance: %w", err)
	}
	if q.deleteSubmissionStmt, err = db.PrepareContext(ctx, deleteSubmission); err != nil {
		return nil, fmt.Errorf("error preparing query DeleteSubmission: %w", err)
	}
	if q.getAdminStatsStmt, err = db.PrepareContext(ctx, getAdminStats); err != nil {
		return nil, fmt.Errorf("error preparing query GetAdminStats: %w", err)
	}
	if q.getAllChallengesInfoStmt, err = db.PrepareContext(ctx, getAllChallengesInfo); err != nil {
		return nil, fmt.Errorf("error preparing query GetAllChallengesInfo: %w", err)
	}
	if q.getAttachmentHashStmt, err = db.PrepareContext(ctx, getAttachmentHash); err != nil {
		return nil, fmt.Errorf("error preparing query GetAttachmentHash: %w", err)
	}
	if q.getBadgesFromTeamStmt, err = db.PrepareContext(ctx, getBadgesFromTeam); err != nil {
		return nil, fmt.Errorf("error preparing query GetBadgesFromTeam: %w", err)
	}
	if q.getCategoriesStmt, err = db.PrepareContext(ctx, getCategories); err != nil {
		return nil, fmt.Errorf("error preparing query GetCategories: %w", err)
	}
	if q.getCategoryStmt, err = db.PrepareContext(ctx, getCategory); err != nil {
		return nil, fmt.Errorf("error preparing query GetCategory: %w", err)
	}
	if q.getChallDockerConfigStmt, err = db.PrepareContext(ctx, getChallDockerConfig); err != nil {
		return nil, fmt.Errorf("error preparing query GetChallDockerConfig: %w", err)
	}
	if q.getChallengeByIDStmt, err = db.PrepareContext(ctx, getChallengeByID); err != nil {
		return nil, fmt.Errorf("error preparing query GetChallengeByID: %w", err)
	}
	if q.getChallengeSolvesStmt, err = db.PrepareContext(ctx, getChallengeSolves); err != nil {
		return nil, fmt.Errorf("error preparing query GetChallengeSolves: %w", err)
	}
	if q.getConfigStmt, err = db.PrepareContext(ctx, getConfig); err != nil {
		return nil, fmt.Errorf("error preparing query GetConfig: %w", err)
	}
	if q.getConfigsStmt, err = db.PrepareContext(ctx, getConfigs); err != nil {
		return nil, fmt.Errorf("error preparing query GetConfigs: %w", err)
	}
	if q.getDockerConfigsByIDStmt, err = db.PrepareContext(ctx, getDockerConfigsByID); err != nil {
		return nil, fmt.Errorf("error preparing query GetDockerConfigsByID: %w", err)
	}
	if q.getFlagsByChallengeStmt, err = db.PrepareContext(ctx, getFlagsByChallenge); err != nil {
		return nil, fmt.Errorf("error preparing query GetFlagsByChallenge: %w", err)
	}
	if q.getHiddenAndAttachmentsStmt, err = db.PrepareContext(ctx, getHiddenAndAttachments); err != nil {
		return nil, fmt.Errorf("error preparing query GetHiddenAndAttachments: %w", err)
	}
	if q.getInstanceStmt, err = db.PrepareContext(ctx, getInstance); err != nil {
		return nil, fmt.Errorf("error preparing query GetInstance: %w", err)
	}
	if q.getInstancesStmt, err = db.PrepareContext(ctx, getInstances); err != nil {
		return nil, fmt.Errorf("error preparing query GetInstances: %w", err)
	}
	if q.getNextInstanceToDeleteStmt, err = db.PrepareContext(ctx, getNextInstanceToDelete); err != nil {
		return nil, fmt.Errorf("error preparing query GetNextInstanceToDelete: %w", err)
	}
	if q.getSubmissionsStmt, err = db.PrepareContext(ctx, getSubmissions); err != nil {
		return nil, fmt.Errorf("error preparing query GetSubmissions: %w", err)
	}
	if q.getTeamByIDStmt, err = db.PrepareContext(ctx, getTeamByID); err != nil {
		return nil, fmt.Errorf("error preparing query GetTeamByID: %w", err)
	}
	if q.getTeamByNameStmt, err = db.PrepareContext(ctx, getTeamByName); err != nil {
		return nil, fmt.Errorf("error preparing query GetTeamByName: %w", err)
	}
	if q.getTeamFromUserStmt, err = db.PrepareContext(ctx, getTeamFromUser); err != nil {
		return nil, fmt.Errorf("error preparing query GetTeamFromUser: %w", err)
	}
	if q.getTeamIDByEmailStmt, err = db.PrepareContext(ctx, getTeamIDByEmail); err != nil {
		return nil, fmt.Errorf("error preparing query GetTeamIDByEmail: %w", err)
	}
	if q.getTeamIDByNameStmt, err = db.PrepareContext(ctx, getTeamIDByName); err != nil {
		return nil, fmt.Errorf("error preparing query GetTeamIDByName: %w", err)
	}
	if q.getTeamMembersStmt, err = db.PrepareContext(ctx, getTeamMembers); err != nil {
		return nil, fmt.Errorf("error preparing query GetTeamMembers: %w", err)
	}
	if q.getTeamSolvesStmt, err = db.PrepareContext(ctx, getTeamSolves); err != nil {
		return nil, fmt.Errorf("error preparing query GetTeamSolves: %w", err)
	}
	if q.getTeamsPreviewStmt, err = db.PrepareContext(ctx, getTeamsPreview); err != nil {
		return nil, fmt.Errorf("error preparing query GetTeamsPreview: %w", err)
	}
	if q.getTeamsScoreboardStmt, err = db.PrepareContext(ctx, getTeamsScoreboard); err != nil {
		return nil, fmt.Errorf("error preparing query GetTeamsScoreboard: %w", err)
	}
	if q.getTeamsScoreboardGraphStmt, err = db.PrepareContext(ctx, getTeamsScoreboardGraph); err != nil {
		return nil, fmt.Errorf("error preparing query GetTeamsScoreboardGraph: %w", err)
	}
	if q.getTotalCategoryChallengesStmt, err = db.PrepareContext(ctx, getTotalCategoryChallenges); err != nil {
		return nil, fmt.Errorf("error preparing query GetTotalCategoryChallenges: %w", err)
	}
	if q.getTotalSubmissionsStmt, err = db.PrepareContext(ctx, getTotalSubmissions); err != nil {
		return nil, fmt.Errorf("error preparing query GetTotalSubmissions: %w", err)
	}
	if q.getTotalTeamsStmt, err = db.PrepareContext(ctx, getTotalTeams); err != nil {
		return nil, fmt.Errorf("error preparing query GetTotalTeams: %w", err)
	}
	if q.getTotalUsersStmt, err = db.PrepareContext(ctx, getTotalUsers); err != nil {
		return nil, fmt.Errorf("error preparing query GetTotalUsers: %w", err)
	}
	if q.getUserByEmailStmt, err = db.PrepareContext(ctx, getUserByEmail); err != nil {
		return nil, fmt.Errorf("error preparing query GetUserByEmail: %w", err)
	}
	if q.getUserByIDStmt, err = db.PrepareContext(ctx, getUserByID); err != nil {
		return nil, fmt.Errorf("error preparing query GetUserByID: %w", err)
	}
	if q.getUserByNameStmt, err = db.PrepareContext(ctx, getUserByName); err != nil {
		return nil, fmt.Errorf("error preparing query GetUserByName: %w", err)
	}
	if q.getUserByTeamIDStmt, err = db.PrepareContext(ctx, getUserByTeamID); err != nil {
		return nil, fmt.Errorf("error preparing query GetUserByTeamID: %w", err)
	}
	if q.getUserIDByEmailStmt, err = db.PrepareContext(ctx, getUserIDByEmail); err != nil {
		return nil, fmt.Errorf("error preparing query GetUserIDByEmail: %w", err)
	}
	if q.getUserIDByNameStmt, err = db.PrepareContext(ctx, getUserIDByName); err != nil {
		return nil, fmt.Errorf("error preparing query GetUserIDByName: %w", err)
	}
	if q.getUserSolvesStmt, err = db.PrepareContext(ctx, getUserSolves); err != nil {
		return nil, fmt.Errorf("error preparing query GetUserSolves: %w", err)
	}
	if q.getUsersStmt, err = db.PrepareContext(ctx, getUsers); err != nil {
		return nil, fmt.Errorf("error preparing query GetUsers: %w", err)
	}
	if q.registerTeamStmt, err = db.PrepareContext(ctx, registerTeam); err != nil {
		return nil, fmt.Errorf("error preparing query RegisterTeam: %w", err)
	}
	if q.registerUserStmt, err = db.PrepareContext(ctx, registerUser); err != nil {
		return nil, fmt.Errorf("error preparing query RegisterUser: %w", err)
	}
	if q.resetTeamPasswordStmt, err = db.PrepareContext(ctx, resetTeamPassword); err != nil {
		return nil, fmt.Errorf("error preparing query ResetTeamPassword: %w", err)
	}
	if q.resetUserPasswordStmt, err = db.PrepareContext(ctx, resetUserPassword); err != nil {
		return nil, fmt.Errorf("error preparing query ResetUserPassword: %w", err)
	}
	if q.submitStmt, err = db.PrepareContext(ctx, submit); err != nil {
		return nil, fmt.Errorf("error preparing query Submit: %w", err)
	}
	if q.toggleChallengesHiddenStmt, err = db.PrepareContext(ctx, toggleChallengesHidden); err != nil {
		return nil, fmt.Errorf("error preparing query ToggleChallengesHidden: %w", err)
	}
	if q.updateChallengeStmt, err = db.PrepareContext(ctx, updateChallenge); err != nil {
		return nil, fmt.Errorf("error preparing query UpdateChallenge: %w", err)
	}
	if q.updateChallengesCategoryStmt, err = db.PrepareContext(ctx, updateChallengesCategory); err != nil {
		return nil, fmt.Errorf("error preparing query UpdateChallengesCategory: %w", err)
	}
	if q.updateConfigStmt, err = db.PrepareContext(ctx, updateConfig); err != nil {
		return nil, fmt.Errorf("error preparing query UpdateConfig: %w", err)
	}
	if q.updateDockerConfigsStmt, err = db.PrepareContext(ctx, updateDockerConfigs); err != nil {
		return nil, fmt.Errorf("error preparing query UpdateDockerConfigs: %w", err)
	}
	if q.updateFlagStmt, err = db.PrepareContext(ctx, updateFlag); err != nil {
		return nil, fmt.Errorf("error preparing query UpdateFlag: %w", err)
	}
	if q.updateInstanceDockerIDStmt, err = db.PrepareContext(ctx, updateInstanceDockerID); err != nil {
		return nil, fmt.Errorf("error preparing query UpdateInstanceDockerID: %w", err)
	}
	if q.updateInstanceExpireStmt, err = db.PrepareContext(ctx, updateInstanceExpire); err != nil {
		return nil, fmt.Errorf("error preparing query UpdateInstanceExpire: %w", err)
	}
	if q.updateTeamStmt, err = db.PrepareContext(ctx, updateTeam); err != nil {
		return nil, fmt.Errorf("error preparing query UpdateTeam: %w", err)
	}
	if q.updateUserStmt, err = db.PrepareContext(ctx, updateUser); err != nil {
		return nil, fmt.Errorf("error preparing query UpdateUser: %w", err)
	}
	if q.userExistsByEmailStmt, err = db.PrepareContext(ctx, userExistsByEmail); err != nil {
		return nil, fmt.Errorf("error preparing query UserExistsByEmail: %w", err)
	}
	return &q, nil
}

func (q *Queries) Close() error {
	var err error
	if q.addTeamMemberStmt != nil {
		if cerr := q.addTeamMemberStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing addTeamMemberStmt: %w", cerr)
		}
	}
	if q.changeUserRoleStmt != nil {
		if cerr := q.changeUserRoleStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing changeUserRoleStmt: %w", cerr)
		}
	}
	if q.checkFlagsStmt != nil {
		if cerr := q.checkFlagsStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing checkFlagsStmt: %w", cerr)
		}
	}
	if q.createAttachmentStmt != nil {
		if cerr := q.createAttachmentStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing createAttachmentStmt: %w", cerr)
		}
	}
	if q.createCategoryStmt != nil {
		if cerr := q.createCategoryStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing createCategoryStmt: %w", cerr)
		}
	}
	if q.createChallengeStmt != nil {
		if cerr := q.createChallengeStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing createChallengeStmt: %w", cerr)
		}
	}
	if q.createConfigStmt != nil {
		if cerr := q.createConfigStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing createConfigStmt: %w", cerr)
		}
	}
	if q.createFlagStmt != nil {
		if cerr := q.createFlagStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing createFlagStmt: %w", cerr)
		}
	}
	if q.createInstanceStmt != nil {
		if cerr := q.createInstanceStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing createInstanceStmt: %w", cerr)
		}
	}
	if q.deleteAttachmentStmt != nil {
		if cerr := q.deleteAttachmentStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing deleteAttachmentStmt: %w", cerr)
		}
	}
	if q.deleteCategoryStmt != nil {
		if cerr := q.deleteCategoryStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing deleteCategoryStmt: %w", cerr)
		}
	}
	if q.deleteChallengeStmt != nil {
		if cerr := q.deleteChallengeStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing deleteChallengeStmt: %w", cerr)
		}
	}
	if q.deleteFlagStmt != nil {
		if cerr := q.deleteFlagStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing deleteFlagStmt: %w", cerr)
		}
	}
	if q.deleteInstanceStmt != nil {
		if cerr := q.deleteInstanceStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing deleteInstanceStmt: %w", cerr)
		}
	}
	if q.deleteSubmissionStmt != nil {
		if cerr := q.deleteSubmissionStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing deleteSubmissionStmt: %w", cerr)
		}
	}
	if q.getAdminStatsStmt != nil {
		if cerr := q.getAdminStatsStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getAdminStatsStmt: %w", cerr)
		}
	}
	if q.getAllChallengesInfoStmt != nil {
		if cerr := q.getAllChallengesInfoStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getAllChallengesInfoStmt: %w", cerr)
		}
	}
	if q.getAttachmentHashStmt != nil {
		if cerr := q.getAttachmentHashStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getAttachmentHashStmt: %w", cerr)
		}
	}
	if q.getBadgesFromTeamStmt != nil {
		if cerr := q.getBadgesFromTeamStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getBadgesFromTeamStmt: %w", cerr)
		}
	}
	if q.getCategoriesStmt != nil {
		if cerr := q.getCategoriesStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getCategoriesStmt: %w", cerr)
		}
	}
	if q.getCategoryStmt != nil {
		if cerr := q.getCategoryStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getCategoryStmt: %w", cerr)
		}
	}
	if q.getChallDockerConfigStmt != nil {
		if cerr := q.getChallDockerConfigStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getChallDockerConfigStmt: %w", cerr)
		}
	}
	if q.getChallengeByIDStmt != nil {
		if cerr := q.getChallengeByIDStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getChallengeByIDStmt: %w", cerr)
		}
	}
	if q.getChallengeSolvesStmt != nil {
		if cerr := q.getChallengeSolvesStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getChallengeSolvesStmt: %w", cerr)
		}
	}
	if q.getConfigStmt != nil {
		if cerr := q.getConfigStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getConfigStmt: %w", cerr)
		}
	}
	if q.getConfigsStmt != nil {
		if cerr := q.getConfigsStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getConfigsStmt: %w", cerr)
		}
	}
	if q.getDockerConfigsByIDStmt != nil {
		if cerr := q.getDockerConfigsByIDStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getDockerConfigsByIDStmt: %w", cerr)
		}
	}
	if q.getFlagsByChallengeStmt != nil {
		if cerr := q.getFlagsByChallengeStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getFlagsByChallengeStmt: %w", cerr)
		}
	}
	if q.getHiddenAndAttachmentsStmt != nil {
		if cerr := q.getHiddenAndAttachmentsStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getHiddenAndAttachmentsStmt: %w", cerr)
		}
	}
	if q.getInstanceStmt != nil {
		if cerr := q.getInstanceStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getInstanceStmt: %w", cerr)
		}
	}
	if q.getInstancesStmt != nil {
		if cerr := q.getInstancesStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getInstancesStmt: %w", cerr)
		}
	}
	if q.getNextInstanceToDeleteStmt != nil {
		if cerr := q.getNextInstanceToDeleteStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getNextInstanceToDeleteStmt: %w", cerr)
		}
	}
	if q.getSubmissionsStmt != nil {
		if cerr := q.getSubmissionsStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getSubmissionsStmt: %w", cerr)
		}
	}
	if q.getTeamByIDStmt != nil {
		if cerr := q.getTeamByIDStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getTeamByIDStmt: %w", cerr)
		}
	}
	if q.getTeamByNameStmt != nil {
		if cerr := q.getTeamByNameStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getTeamByNameStmt: %w", cerr)
		}
	}
	if q.getTeamFromUserStmt != nil {
		if cerr := q.getTeamFromUserStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getTeamFromUserStmt: %w", cerr)
		}
	}
	if q.getTeamIDByEmailStmt != nil {
		if cerr := q.getTeamIDByEmailStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getTeamIDByEmailStmt: %w", cerr)
		}
	}
	if q.getTeamIDByNameStmt != nil {
		if cerr := q.getTeamIDByNameStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getTeamIDByNameStmt: %w", cerr)
		}
	}
	if q.getTeamMembersStmt != nil {
		if cerr := q.getTeamMembersStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getTeamMembersStmt: %w", cerr)
		}
	}
	if q.getTeamSolvesStmt != nil {
		if cerr := q.getTeamSolvesStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getTeamSolvesStmt: %w", cerr)
		}
	}
	if q.getTeamsPreviewStmt != nil {
		if cerr := q.getTeamsPreviewStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getTeamsPreviewStmt: %w", cerr)
		}
	}
	if q.getTeamsScoreboardStmt != nil {
		if cerr := q.getTeamsScoreboardStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getTeamsScoreboardStmt: %w", cerr)
		}
	}
	if q.getTeamsScoreboardGraphStmt != nil {
		if cerr := q.getTeamsScoreboardGraphStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getTeamsScoreboardGraphStmt: %w", cerr)
		}
	}
	if q.getTotalCategoryChallengesStmt != nil {
		if cerr := q.getTotalCategoryChallengesStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getTotalCategoryChallengesStmt: %w", cerr)
		}
	}
	if q.getTotalSubmissionsStmt != nil {
		if cerr := q.getTotalSubmissionsStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getTotalSubmissionsStmt: %w", cerr)
		}
	}
	if q.getTotalTeamsStmt != nil {
		if cerr := q.getTotalTeamsStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getTotalTeamsStmt: %w", cerr)
		}
	}
	if q.getTotalUsersStmt != nil {
		if cerr := q.getTotalUsersStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getTotalUsersStmt: %w", cerr)
		}
	}
	if q.getUserByEmailStmt != nil {
		if cerr := q.getUserByEmailStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getUserByEmailStmt: %w", cerr)
		}
	}
	if q.getUserByIDStmt != nil {
		if cerr := q.getUserByIDStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getUserByIDStmt: %w", cerr)
		}
	}
	if q.getUserByNameStmt != nil {
		if cerr := q.getUserByNameStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getUserByNameStmt: %w", cerr)
		}
	}
	if q.getUserByTeamIDStmt != nil {
		if cerr := q.getUserByTeamIDStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getUserByTeamIDStmt: %w", cerr)
		}
	}
	if q.getUserIDByEmailStmt != nil {
		if cerr := q.getUserIDByEmailStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getUserIDByEmailStmt: %w", cerr)
		}
	}
	if q.getUserIDByNameStmt != nil {
		if cerr := q.getUserIDByNameStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getUserIDByNameStmt: %w", cerr)
		}
	}
	if q.getUserSolvesStmt != nil {
		if cerr := q.getUserSolvesStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getUserSolvesStmt: %w", cerr)
		}
	}
	if q.getUsersStmt != nil {
		if cerr := q.getUsersStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getUsersStmt: %w", cerr)
		}
	}
	if q.registerTeamStmt != nil {
		if cerr := q.registerTeamStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing registerTeamStmt: %w", cerr)
		}
	}
	if q.registerUserStmt != nil {
		if cerr := q.registerUserStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing registerUserStmt: %w", cerr)
		}
	}
	if q.resetTeamPasswordStmt != nil {
		if cerr := q.resetTeamPasswordStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing resetTeamPasswordStmt: %w", cerr)
		}
	}
	if q.resetUserPasswordStmt != nil {
		if cerr := q.resetUserPasswordStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing resetUserPasswordStmt: %w", cerr)
		}
	}
	if q.submitStmt != nil {
		if cerr := q.submitStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing submitStmt: %w", cerr)
		}
	}
	if q.toggleChallengesHiddenStmt != nil {
		if cerr := q.toggleChallengesHiddenStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing toggleChallengesHiddenStmt: %w", cerr)
		}
	}
	if q.updateChallengeStmt != nil {
		if cerr := q.updateChallengeStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing updateChallengeStmt: %w", cerr)
		}
	}
	if q.updateChallengesCategoryStmt != nil {
		if cerr := q.updateChallengesCategoryStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing updateChallengesCategoryStmt: %w", cerr)
		}
	}
	if q.updateConfigStmt != nil {
		if cerr := q.updateConfigStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing updateConfigStmt: %w", cerr)
		}
	}
	if q.updateDockerConfigsStmt != nil {
		if cerr := q.updateDockerConfigsStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing updateDockerConfigsStmt: %w", cerr)
		}
	}
	if q.updateFlagStmt != nil {
		if cerr := q.updateFlagStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing updateFlagStmt: %w", cerr)
		}
	}
	if q.updateInstanceDockerIDStmt != nil {
		if cerr := q.updateInstanceDockerIDStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing updateInstanceDockerIDStmt: %w", cerr)
		}
	}
	if q.updateInstanceExpireStmt != nil {
		if cerr := q.updateInstanceExpireStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing updateInstanceExpireStmt: %w", cerr)
		}
	}
	if q.updateTeamStmt != nil {
		if cerr := q.updateTeamStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing updateTeamStmt: %w", cerr)
		}
	}
	if q.updateUserStmt != nil {
		if cerr := q.updateUserStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing updateUserStmt: %w", cerr)
		}
	}
	if q.userExistsByEmailStmt != nil {
		if cerr := q.userExistsByEmailStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing userExistsByEmailStmt: %w", cerr)
		}
	}
	return err
}

func (q *Queries) exec(ctx context.Context, stmt *sql.Stmt, query string, args ...interface{}) (sql.Result, error) {
	switch {
	case stmt != nil && q.tx != nil:
		return q.tx.StmtContext(ctx, stmt).ExecContext(ctx, args...)
	case stmt != nil:
		return stmt.ExecContext(ctx, args...)
	default:
		return q.db.ExecContext(ctx, query, args...)
	}
}

func (q *Queries) query(ctx context.Context, stmt *sql.Stmt, query string, args ...interface{}) (*sql.Rows, error) {
	switch {
	case stmt != nil && q.tx != nil:
		return q.tx.StmtContext(ctx, stmt).QueryContext(ctx, args...)
	case stmt != nil:
		return stmt.QueryContext(ctx, args...)
	default:
		return q.db.QueryContext(ctx, query, args...)
	}
}

func (q *Queries) queryRow(ctx context.Context, stmt *sql.Stmt, query string, args ...interface{}) *sql.Row {
	switch {
	case stmt != nil && q.tx != nil:
		return q.tx.StmtContext(ctx, stmt).QueryRowContext(ctx, args...)
	case stmt != nil:
		return stmt.QueryRowContext(ctx, args...)
	default:
		return q.db.QueryRowContext(ctx, query, args...)
	}
}

type Queries struct {
	db                             DBTX
	tx                             *sql.Tx
	addTeamMemberStmt              *sql.Stmt
	changeUserRoleStmt             *sql.Stmt
	checkFlagsStmt                 *sql.Stmt
	createAttachmentStmt           *sql.Stmt
	createCategoryStmt             *sql.Stmt
	createChallengeStmt            *sql.Stmt
	createConfigStmt               *sql.Stmt
	createFlagStmt                 *sql.Stmt
	createInstanceStmt             *sql.Stmt
	deleteAttachmentStmt           *sql.Stmt
	deleteCategoryStmt             *sql.Stmt
	deleteChallengeStmt            *sql.Stmt
	deleteFlagStmt                 *sql.Stmt
	deleteInstanceStmt             *sql.Stmt
	deleteSubmissionStmt           *sql.Stmt
	getAdminStatsStmt              *sql.Stmt
	getAllChallengesInfoStmt       *sql.Stmt
	getAttachmentHashStmt          *sql.Stmt
	getBadgesFromTeamStmt          *sql.Stmt
	getCategoriesStmt              *sql.Stmt
	getCategoryStmt                *sql.Stmt
	getChallDockerConfigStmt       *sql.Stmt
	getChallengeByIDStmt           *sql.Stmt
	getChallengeSolvesStmt         *sql.Stmt
	getConfigStmt                  *sql.Stmt
	getConfigsStmt                 *sql.Stmt
	getDockerConfigsByIDStmt       *sql.Stmt
	getFlagsByChallengeStmt        *sql.Stmt
	getHiddenAndAttachmentsStmt    *sql.Stmt
	getInstanceStmt                *sql.Stmt
	getInstancesStmt               *sql.Stmt
	getNextInstanceToDeleteStmt    *sql.Stmt
	getSubmissionsStmt             *sql.Stmt
	getTeamByIDStmt                *sql.Stmt
	getTeamByNameStmt              *sql.Stmt
	getTeamFromUserStmt            *sql.Stmt
	getTeamIDByEmailStmt           *sql.Stmt
	getTeamIDByNameStmt            *sql.Stmt
	getTeamMembersStmt             *sql.Stmt
	getTeamSolvesStmt              *sql.Stmt
	getTeamsPreviewStmt            *sql.Stmt
	getTeamsScoreboardStmt         *sql.Stmt
	getTeamsScoreboardGraphStmt    *sql.Stmt
	getTotalCategoryChallengesStmt *sql.Stmt
	getTotalSubmissionsStmt        *sql.Stmt
	getTotalTeamsStmt              *sql.Stmt
	getTotalUsersStmt              *sql.Stmt
	getUserByEmailStmt             *sql.Stmt
	getUserByIDStmt                *sql.Stmt
	getUserByNameStmt              *sql.Stmt
	getUserByTeamIDStmt            *sql.Stmt
	getUserIDByEmailStmt           *sql.Stmt
	getUserIDByNameStmt            *sql.Stmt
	getUserSolvesStmt              *sql.Stmt
	getUsersStmt                   *sql.Stmt
	registerTeamStmt               *sql.Stmt
	registerUserStmt               *sql.Stmt
	resetTeamPasswordStmt          *sql.Stmt
	resetUserPasswordStmt          *sql.Stmt
	submitStmt                     *sql.Stmt
	toggleChallengesHiddenStmt     *sql.Stmt
	updateChallengeStmt            *sql.Stmt
	updateChallengesCategoryStmt   *sql.Stmt
	updateConfigStmt               *sql.Stmt
	updateDockerConfigsStmt        *sql.Stmt
	updateFlagStmt                 *sql.Stmt
	updateInstanceDockerIDStmt     *sql.Stmt
	updateInstanceExpireStmt       *sql.Stmt
	updateTeamStmt                 *sql.Stmt
	updateUserStmt                 *sql.Stmt
	userExistsByEmailStmt          *sql.Stmt
}

func (q *Queries) WithTx(tx *sql.Tx) *Queries {
	return &Queries{
		db:                             tx,
		tx:                             tx,
		addTeamMemberStmt:              q.addTeamMemberStmt,
		changeUserRoleStmt:             q.changeUserRoleStmt,
		checkFlagsStmt:                 q.checkFlagsStmt,
		createAttachmentStmt:           q.createAttachmentStmt,
		createCategoryStmt:             q.createCategoryStmt,
		createChallengeStmt:            q.createChallengeStmt,
		createConfigStmt:               q.createConfigStmt,
		createFlagStmt:                 q.createFlagStmt,
		createInstanceStmt:             q.createInstanceStmt,
		deleteAttachmentStmt:           q.deleteAttachmentStmt,
		deleteCategoryStmt:             q.deleteCategoryStmt,
		deleteChallengeStmt:            q.deleteChallengeStmt,
		deleteFlagStmt:                 q.deleteFlagStmt,
		deleteInstanceStmt:             q.deleteInstanceStmt,
		deleteSubmissionStmt:           q.deleteSubmissionStmt,
		getAdminStatsStmt:              q.getAdminStatsStmt,
		getAllChallengesInfoStmt:       q.getAllChallengesInfoStmt,
		getAttachmentHashStmt:          q.getAttachmentHashStmt,
		getBadgesFromTeamStmt:          q.getBadgesFromTeamStmt,
		getCategoriesStmt:              q.getCategoriesStmt,
		getCategoryStmt:                q.getCategoryStmt,
		getChallDockerConfigStmt:       q.getChallDockerConfigStmt,
		getChallengeByIDStmt:           q.getChallengeByIDStmt,
		getChallengeSolvesStmt:         q.getChallengeSolvesStmt,
		getConfigStmt:                  q.getConfigStmt,
		getConfigsStmt:                 q.getConfigsStmt,
		getDockerConfigsByIDStmt:       q.getDockerConfigsByIDStmt,
		getFlagsByChallengeStmt:        q.getFlagsByChallengeStmt,
		getHiddenAndAttachmentsStmt:    q.getHiddenAndAttachmentsStmt,
		getInstanceStmt:                q.getInstanceStmt,
		getInstancesStmt:               q.getInstancesStmt,
		getNextInstanceToDeleteStmt:    q.getNextInstanceToDeleteStmt,
		getSubmissionsStmt:             q.getSubmissionsStmt,
		getTeamByIDStmt:                q.getTeamByIDStmt,
		getTeamByNameStmt:              q.getTeamByNameStmt,
		getTeamFromUserStmt:            q.getTeamFromUserStmt,
		getTeamIDByEmailStmt:           q.getTeamIDByEmailStmt,
		getTeamIDByNameStmt:            q.getTeamIDByNameStmt,
		getTeamMembersStmt:             q.getTeamMembersStmt,
		getTeamSolvesStmt:              q.getTeamSolvesStmt,
		getTeamsPreviewStmt:            q.getTeamsPreviewStmt,
		getTeamsScoreboardStmt:         q.getTeamsScoreboardStmt,
		getTeamsScoreboardGraphStmt:    q.getTeamsScoreboardGraphStmt,
		getTotalCategoryChallengesStmt: q.getTotalCategoryChallengesStmt,
		getTotalSubmissionsStmt:        q.getTotalSubmissionsStmt,
		getTotalTeamsStmt:              q.getTotalTeamsStmt,
		getTotalUsersStmt:              q.getTotalUsersStmt,
		getUserByEmailStmt:             q.getUserByEmailStmt,
		getUserByIDStmt:                q.getUserByIDStmt,
		getUserByNameStmt:              q.getUserByNameStmt,
		getUserByTeamIDStmt:            q.getUserByTeamIDStmt,
		getUserIDByEmailStmt:           q.getUserIDByEmailStmt,
		getUserIDByNameStmt:            q.getUserIDByNameStmt,
		getUserSolvesStmt:              q.getUserSolvesStmt,
		getUsersStmt:                   q.getUsersStmt,
		registerTeamStmt:               q.registerTeamStmt,
		registerUserStmt:               q.registerUserStmt,
		resetTeamPasswordStmt:          q.resetTeamPasswordStmt,
		resetUserPasswordStmt:          q.resetUserPasswordStmt,
		submitStmt:                     q.submitStmt,
		toggleChallengesHiddenStmt:     q.toggleChallengesHiddenStmt,
		updateChallengeStmt:            q.updateChallengeStmt,
		updateChallengesCategoryStmt:   q.updateChallengesCategoryStmt,
		updateConfigStmt:               q.updateConfigStmt,
		updateDockerConfigsStmt:        q.updateDockerConfigsStmt,
		updateFlagStmt:                 q.updateFlagStmt,
		updateInstanceDockerIDStmt:     q.updateInstanceDockerIDStmt,
		updateInstanceExpireStmt:       q.updateInstanceExpireStmt,
		updateTeamStmt:                 q.updateTeamStmt,
		updateUserStmt:                 q.updateUserStmt,
		userExistsByEmailStmt:          q.userExistsByEmailStmt,
	}
}
